//! Autogenerated weights for pallet_dapi
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-05, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/massbit-collator
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_dapi
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/dapi/src/weights.rs
// --template
// ./benchmarking/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_dapi.
pub trait WeightInfo {
	#[rustfmt::skip]
	fn register_project() -> Weight;
	#[rustfmt::skip]
	fn deposit_project() -> Weight;
	#[rustfmt::skip]
	fn withdraw_project_deposit() -> Weight;
	#[rustfmt::skip]
	fn unregister_provider() -> Weight;
}

/// Weights for pallet_dapi using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn register_project() -> Weight {
		(24_736_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn deposit_project() -> Weight {
		(23_274_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn withdraw_project_deposit() -> Weight {
		(23_674_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	#[rustfmt::skip]
	fn unregister_provider() -> Weight {
		(18_615_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: Dapi ChainIds (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn register_project() -> Weight {
		(24_736_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn deposit_project() -> Weight {
		(23_274_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Projects (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	#[rustfmt::skip]
	fn withdraw_project_deposit() -> Weight {
		(23_674_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Dapi Providers (r:1 w:1)
	// Storage: DapiStaking RegisteredProviders (r:1 w:1)
	// Storage: DapiStaking CurrentEra (r:1 w:0)
	#[rustfmt::skip]
	fn unregister_provider() -> Weight {
		(18_615_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
