[workspace]
members = [
    'node',
    'pallets/block-reward',
    'pallets/dapi',
    'pallets/dapi-staking',
    'pallets/fisherman',
    'pallets/oracle',
    'runtime/local',
]
[profile.release]
panic = 'unwind'
